#!/usr/bin/env python
"""
Plot GC / MFE / novelty distributions for Real, M1, M2 (cVAE & cGAN) and M3 (RL).
Reads the unified feature table generated by prepare_multi_model_features.py.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ORDER = [
    ("Real (eval)", "#1f77b4"),
    ("M1 top-k", "#ff7f0e"),
    ("M2 cVAE", "#2ca02c"),
    ("M2 cGAN", "#d62728"),
    ("M3 RL", "#9467bd"),
]


def load_data(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    df = df[df["source"].isin([name for name, _ in ORDER])]
    return df


def _hist(values: pd.Series, bins: int, rng: tuple[float, float]):
    return np.histogram(values, bins=bins, range=rng, density=True)


def plot_hist(df: pd.DataFrame, feature: str, xlabel: str, out_path: Path, bins: int = 80):
    sub = df[["source", feature]].dropna()
    if sub.empty:
        print(f"[WARN] feature '{feature}' has no data; skip plotting")
        return
    overall = sub[feature]
    rng = (overall.min(), overall.max())
    plt.figure(figsize=(7, 4))
    for label, color in ORDER:
        vals = sub[sub["source"] == label][feature].dropna()
        if not len(vals):
            continue
        plt.hist(
            vals,
            bins=bins,
            range=rng,
            density=True,
            histtype="step",
            linewidth=1.5,
            label=label,
            color=color,
        )
    plt.xlabel(xlabel)
    plt.ylabel("Density")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    print(f"[OK] wrote {out_path}")


def plot_novelty_scatter(df: pd.DataFrame, out_path: Path, max_points: int = 2000):
    plt.figure(figsize=(6, 5))
    for label, color in ORDER:
        sub = df[df["source"] == label][["novelty", "score_pred"]].dropna()
        if not len(sub):
            continue
        if len(sub) > max_points:
            sub = sub.sample(max_points, random_state=0)
        plt.scatter(
            sub["novelty"],
            sub["score_pred"],
            s=8,
            alpha=0.5,
            label=label,
            color=color,
        )
    plt.xlabel("Novelty")
    plt.ylabel("score_pred")
    plt.legend(markerscale=1.5)
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    print(f"[OK] wrote {out_path}")


def summarize_feature(df: pd.DataFrame, feature: str):
    print(f"\n=== Stats: {feature} ===")
    for label, _ in ORDER:
        vals = df[df["source"] == label][feature].dropna()
        if not len(vals):
            print(f"{label}: n=0")
            continue
        print(
            f"{label}: n={len(vals)}, "
            f"mean={vals.mean():.4f}, "
            f"std={vals.std():.4f}, "
            f"q10={vals.quantile(0.10):.4f}, "
            f"q50={vals.quantile(0.50):.4f}, "
            f"q90={vals.quantile(0.90):.4f}"
        )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--input",
        default="data/derived/multi_model/all_models_features.csv",
        help="Unified feature table",
    )
    ap.add_argument("--outdir", default="figs/outputs", help="Directory for plots")
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[1]
    df = load_data(root / args.input)
    outdir = root / args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    plot_hist(df, "gc", "GC content", outdir / "fig3_multi_gc.png", bins=60)
    plot_hist(df, "mfe_utr5", "mfe_utr5", outdir / "fig3_multi_mfe_utr5.png", bins=60)
    plot_hist(df, "mfe_utr3", "mfe_utr3", outdir / "fig3_multi_mfe_utr3.png", bins=60)
    plot_novelty_scatter(df, outdir / "fig3_multi_novelty_vs_score.png")

    summarize_feature(df, "gc")
    summarize_feature(df, "mfe_utr5")
    summarize_feature(df, "mfe_utr3")
    summarize_feature(df, "novelty")


if __name__ == "__main__":
    main()
